# Generated by Django 5.1.1 on 2024-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_user_alter_car_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
